### PR TITLE
feat: trim empty space

### PR DESCRIPTION
**Pull request by saphirahopeseeker**
Tolerates spaces which are hard to see and usually copied w/o realization.

The UI should be understanding and not frustrate the user since to a person a space shouldn't mean anything (in this context)

### CODE REVIEW

**Comment by atmoio** [comment]
Thanks @standardorcawolf, assigning to @johnny243.

**Comment by saphirahopeseeker** [comment]
😁️On Fri, 2021-03-26 at 05:21 -0700, Mo Bitar wrote:

**Review by johnny243 — APPROVED** [review]
Looks good 👍🏽 Don't forget to build and increment `package.json` version

**Comment by saphirahopeseeker** [comment]
Closed, since I wasn't able to make the requested changes in this web commit. See https://github.com/standardnotes/mfa-link/pull/18

**Pull request closed without merging**
