### PR TITLE
feat: export secret key

### PR DESCRIPTION
**Pull request by dagjaneiro**
Added the export secret button.

Tested on web and desktop.

Web:
2fa_web

Desktop:
2fa_desktop

## Updated screenshot

image

Closes standardnotes/bounties#12

### CODE REVIEW

**Comment by atmoio** [comment]
Sorry just caught this now—but I think we should definitely be able to do this without a third-party dependency. We do this in Action Bar for the Save action: https://github.com/sn-extensions/action-bar/blob/master/app/js/controllers/home.js#L119 and also in FileSafe to download files: https://github.com/standardnotes/filesafe-js/blob/master/src/lib/util/Utils.js#L12

**Comment by dagjaneiro** [comment]
Sure, no problem. I'll remove the dependency and implement it in a similar manner.

**Comment by dagjaneiro** [comment]
Followed your advice, removed the dependency and opted for a simpler solution.

**Comment by atmoio** [comment]
Nice, I'll take a look at all the changes early next week.

**Pull request merged**
